// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQbqsZQ8pMuT4NhTzy7CMRoHUkztKfoQ',
    appId: '1:571728975971:web:276fad9c98e69965d7c056',
    messagingSenderId: '571728975971',
    projectId: 'padelmarcheofficialflutter',
    authDomain: 'padelmarcheofficialflutter.firebaseapp.com',
    storageBucket: 'padelmarcheofficialflutter.appspot.com',
    measurementId: 'G-RRVCHB5S45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3tM4UHzlKk3-cJjE2FDaNC2pyR5y3hI',
    appId: '1:571728975971:android:9ad63236c59a07c0d7c056',
    messagingSenderId: '571728975971',
    projectId: 'padelmarcheofficialflutter',
    storageBucket: 'padelmarcheofficialflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDyfpyg7HowvGJDOj5KBM84ftiCwUB3Rc',
    appId: '1:571728975971:ios:d5aedd93f50f4179d7c056',
    messagingSenderId: '571728975971',
    projectId: 'padelmarcheofficialflutter',
    storageBucket: 'padelmarcheofficialflutter.appspot.com',
    iosBundleId: 'com.example.padelmarcheofficialflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDyfpyg7HowvGJDOj5KBM84ftiCwUB3Rc',
    appId: '1:571728975971:ios:8d117efb0fc53916d7c056',
    messagingSenderId: '571728975971',
    projectId: 'padelmarcheofficialflutter',
    storageBucket: 'padelmarcheofficialflutter.appspot.com',
    iosBundleId: 'com.example.padelmarcheofficialflutter.RunnerTests',
  );
}
